'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RadminVPN_Helper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a @echo off
        '''
        '''echo RadminVPN Helper Cleaner
        '''
        '''timeout 2
        '''
        '''DEL &quot;C:\Windows\Temp\*.*&quot; /F /Q /S
        '''
        '''DEL &quot;C:\Users\%USERNAME%\AppData\Local\Temp\*.*&quot; /F /Q /S
        '''
        '''DEL &quot;C:\Windows\Prefetch\*.*&quot; /F /Q /S
        '''
        '''::DEL &quot;%windir%\system32\dllcache\*.*&quot; /F /Q /S
        '''
        '''::DEL &quot;%SysteDrive%\Temp\*.*&quot; /F /Q /S
        '''
        '''DEL &quot;%USERPROFILE%\Local Settings\Temp\*.*&quot; /F /Q /S
        '''
        '''::DEL &quot;%USERPROFILE%\Local Settings\Temporary Internet Files\*.*&quot; /F /Q /S
        '''
        '''echo Job Finished at %time%
        '''
        '''pause
        '''exit.
        '''</summary>
        Friend ReadOnly Property cleaner() As String
            Get
                Return ResourceManager.GetString("cleaner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft1603() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft1603", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a @echo off
        '''
        '''netsh int ip reset
        '''
        '''ipconfig /release
        '''
        '''ipconfig /all
        '''
        '''ipconfig /flushdns
        '''
        '''ipconfig /renew
        '''
        '''netsh int ip set dns
        '''
        '''netsh winsock reset
        '''
        '''echo Internet Settings have been resetted correctly. Please restart your Computer
        '''
        '''pause
        '''exit.
        '''</summary>
        Friend ReadOnly Property reset_internet() As String
            Get
                Return ResourceManager.GetString("reset_internet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a @echo off
        '''wmic product get name &gt; C:\wmicRadminHelper.txt.
        '''</summary>
        Friend ReadOnly Property wmicRadminHelper() As String
            Get
                Return ResourceManager.GetString("wmicRadminHelper", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
